In [7]:
import pandas as pd

In [9]:
data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [13]:
data = [1,2,3,4]
i = ['A','B','C','D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [17]:
data = {'a':10, 'b':20, 'c':30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [19]:
series.replace(20,100)

a     10
b    100
c     30
dtype: int64

In [21]:
import numpy as np

data = np.array([100,200,300])
series = pd.Series(data,index=['a','b','c'])
print(series)

a    100
b    200
c    300
dtype: int32


In [27]:
import pandas as pd

data = {'Name': ['Alice','Bob','Mary'],'Age':[25,30,34],
        'Country':["USA","UK","AUS"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34     AUS


In [29]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=['A','B','c'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  c
0  1  2  3
1  4  5  6
2  7  8  9


In [31]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array)
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [35]:
data = [[1,'Alice',25],[2,'Bob',30],[3,'Mary',34]]
print(data)
df = pd.DataFrame(data,columns=['ID','Name','Age'])
print(df)

[[1, 'Alice', 25], [2, 'Bob', 30], [3, 'Mary', 34]]
   ID   Name  Age
0   1  Alice   25
1   2    Bob   30
2   3   Mary   34


In [8]:
import pandas as pd
iris_df = pd.read_csv("iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [24]:
import pandas as pd
iris_df = pd.read_excel("iris.xlsx")
print(iris_df)

FileNotFoundError: [Errno 2] No such file or directory: 'iris.xlsx'